import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Currency Converter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen px-2.5 py-5 sm:px-0  sm:max-w-6/12 mx-auto">
        {children}
      </body>
    </html>
  );
}
